name: GitHub Actions (Demo CI/CD)

on:
  push:
    branches: #событие по которому запускают работника
      - master

jobs:
  build_prg:  #название работы
    runs-on: ubuntu-latest #ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 #Checkout code

#      - name: Check available Python
#        run: python -V
#
#      - name: Check available Pip
#        run: python -m pip -V
#
#      - name: Install dependencies
#        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies
        run: |
          echo $GITHUB_WORKSPACE;
          if [ -f $GITHUB_WORKSPACE/requirements.txt ]; then 
            echo "FOUND REQUIREMENTS.TXT"
          else
            echo "Not found requirements.txt"
          fi

#      - name: Check installed dependencies
#        run: python -m pip freeze

