name: GitHub Actions (Demo CI/CD)

on:
  push:
    branches: #событие по которому запускают работника
      - master

jobs:
  build_prg:  #название работы
    runs-on: ubuntu-20.04 # ubuntu-latest - есть ошибка вместо 20.04 устанавливается 22.04
    steps:
      - uses: actions/checkout@v3 #Checkout code

      - name: Check available Python
        run: python -V

      - name: Check available Pip
        run: python -m pip -V

#      #версии могут не подходить под текущий python
#      - name: Install dependencies
#        run: |
#          if [ -f $GITHUB_WORKSPACE/requirements.txt ]; then
#            echo "FOUND REQUIREMENTS.TXT"
#            pip install -r $GITHUB_WORKSPACE/requirements.txt;
#          else
#            echo "Not found requirements.txt";
#          fi

      - name: Install Dependencies
        run: | 
          python -m pip install flask;
          python -m pip install flask-blueprint;
          python -m pip install flasgger;

      - name: Check installed dependencies
        run: python -m pip freeze

