name: GitHub Actions (Demo CI/CD)

on:
  push:
    branches: #событи по которому запускают работника
      - main

jobs:
  build_prg:  #название работы
    runs-on: ubuntu-20.04
    steps:
#      - name: Checkout code
#      - uses: actions/checkout@v3 #Checkout code

      - name: Print Hello
        run: echo "Hello Alex"

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt;


